# Generated by Django 4.2.10 on 2024-02-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='otsosi_mne',
        ),
    ]
