# Generated by Django 4.2.10 on 2024-03-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_categories_otsosi_mne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
